<a href="https://colab.research.google.com/github/Srishti6125/XOR-Neural-Network/blob/main/XOR_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###XOR Neural Network
(NumPy vs Tf-Keras vs Pytorch)

#### Numpy

In [17]:
# libraries
import numpy as np

In [23]:
# neural network using numpy

# inputs
X= np.array( [[0, 0], [0, 1], [1, 0], [1, 1]] )

# Outputs (XOR)
y = np.array( [[0], [1], [1], [0]] )

input_dim = 2     # 2 inputs (input layer)
hidden_dim = 2    # two hidden neurons (hidden layer)
output_dim = 1    # single output (output layer)

# Hyperparameters
learning_rate = 1.0
epochs = 5000

# small random values
np.random.seed(42)

W1 = np.random.uniform(-1, 1, (input_dim, hidden_dim))     # (2 x 2)
W2 = np.random.uniform(-1, 1, (hidden_dim, output_dim))    # (2 x 1)

b1 = np.zeros((1, hidden_dim))    # (1 x 2)
b2 = np.zeros((1, output_dim))    # (1 x 1)

# activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(a):        # a is sigmoid(z)
    return a * (1 - a)

# training loop

for epoch in range(epochs):

    # forward pass
    # Hidden layer
    z1 = np.dot(X, W1) + b1        # (4 x 2)
    a1 = sigmoid(z1)               # (4 x 2)
    # Output layer
    z2 = np.dot(a1, W2) + b2       # (4 x 1)
    a2 = sigmoid(z2)               # (4 x 1) predictions

    # defining loss - binary cross entropy loss
    eps = 1e-8      # small epsilon to avoid log(0)
    loss = -np.mean(y * np.log(a2 + eps) + (1 - y) * np.log(1 - a2 + eps))

    # back propagation
    # Output layer error
    dz2 = a2 - y   # (4 x 1)

    # Gradients for W2 and b2
    dW2 = np.dot(a1.T, dz2) / X.shape[0]           # (2 x 1)
    db2 = np.mean(dz2, axis=0, keepdims=True)      # (1 x 1)

    # Hidden layer error
    dz1 = np.dot(dz2, W2.T) * sigmoid_derivative(a1)  # (4 x 2)

    # Gradients for W1 and b1
    dW1 = np.dot(X.T, dz1) / X.shape[0]            # (2 x 2)
    db1 = np.mean(dz1, axis=0, keepdims=True)      # (1 x 2)

    # updating weights
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss:.4f}")

#  Evaluating trained model
print("\nFinal predictions after training:")
z1 = np.dot(X, W1) + b1
a1 = sigmoid(z1)
z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

print("Inputs:\n", X)
print("True labels:\n", y)
print("\n\nRaw outputs (probabilities):\n", a2)
print("Rounded predictions:\n", np.round(a2))

Epoch 1000/5000, Loss: 0.0567
Epoch 2000/5000, Loss: 0.0138
Epoch 3000/5000, Loss: 0.0077
Epoch 4000/5000, Loss: 0.0053
Epoch 5000/5000, Loss: 0.0041

Final predictions after training:
Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
True labels:
 [[0]
 [1]
 [1]
 [0]]


Raw outputs (probabilities):
 [[0.00359115]
 [0.99524315]
 [0.99524401]
 [0.00319889]]
Rounded predictions:
 [[0.]
 [1.]
 [1.]
 [0.]]


#### Keras-Tensorflow

In [28]:
# libraries

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

In [33]:
# neural network using tensorflow-keras

# Input
X = np.array( [[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)

# Output
y = np.array( [[0], [1], [1], [0]], dtype=np.float32)

# Building model
model = Sequential([
    Dense(2, activation='tanh', input_dim=2),  # hidden layer with 2 neurons
    Dense(1, activation='sigmoid')             # output layer
])
optimizer = Adam(learning_rate=0.1)
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# earlystopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

# Training model
history = model.fit(
    X, y,
    epochs=5000,
    batch_size=4,
    verbose=0,
    callbacks=[early_stop]
)

# Evaluation and prediction
loss, acc = model.evaluate(X, y, verbose=0)
print(f"\nFinal training loss: {loss:.6f}, accuracy: {acc:.4f}")

y_pred = model.predict(X)
print("Inputs:\n", X)
print("True labels:\n", y)
print("\n\nRaw outputs (probabilities):\n", y_pred)
print("Rounded predictions:\n", np.round(y_pred))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

/usr/local/lib/python3.12/dist-packages/keras/src/callbacks/early_stopping.py:99: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss
  current = self.get_monitor_value(logs)



Final training loss: 0.000014, accuracy: 1.0000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
True labels:
 [[0.]
 [1.]
 [1.]
 [0.]]


Raw outputs (probabilities):
 [[1.7970815e-05]
 [9.9999118e-01]
 [9.9999106e-01]
 [2.0009307e-05]]
Rounded predictions:
 [[0.]
 [1.]
 [1.]
 [0.]]


####Pytorch

In [ ]:
# libraries

import torch
import torch.nn as nn
import torch.optim as optim

In [32]:
# Features (x and y)

x = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
y = torch.tensor([[0],[1],[1],[0]], dtype= torch.float32)

# building neural network

class xor_nn(nn.Module):   #base class
  def __init__(self):
    super(xor_nn, self).__init__()
    self.fc1 = nn.Linear(2,4) # input layer
    self.tanh = nn.Tanh()
    self.fc2 = nn.Linear(4,1) # output layer
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x= self.fc1(x)
    x= self.tanh(x)
    x= self.fc2(x)
    x= self.sigmoid(x)
    return x

# creating model
model = xor_nn()

# defining binary cross entropy loss and adam optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

# defining early stopping parameters
best_loss = float('inf')
patience = 200
counter = 0

# training loop
for epoch in range(5000):

    # Forward pass
    outputs = model(x)
    loss = criterion(outputs, y)  #loss calculation

    # Backward pass
    optimizer.zero_grad() #clears memory
    loss.backward()

    # Update weights
    optimizer.step()

    # Early stopping
    if loss.item() < best_loss:
        best_loss = loss.item()
        counter = 0
    else:
        counter += 1

    if counter >= patience:
        print(f"Early stopping at epoch {epoch}")
        break

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# testing model
with torch.no_grad():
    predictions = model(x)
    print("Inputs:\n",x)
    print("True labels:\n", y)
    print("\n\nRaw outputs (probabilities):\n",predictions)
    print("Rounded predictions:\n", torch.round(predictions))

Epoch 0, Loss: 0.708472728729248
Epoch 1000, Loss: 0.00014540244592353702
Epoch 2000, Loss: 4.3785039451904595e-05
Epoch 3000, Loss: 1.946992961165961e-05
Epoch 4000, Loss: 1.0033867511083372e-05
Inputs:
 tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
True labels:
 tensor([[0.],
        [1.],
        [1.],
        [0.]])


Raw outputs (probabilities):
 tensor([[9.3700e-08],
        [1.0000e+00],
        [9.9999e-01],
        [8.9234e-06]])
Rounded predictions:
 tensor([[0.],
        [1.],
        [1.],
        [0.]])


###**Summary**

“All frameworks use the same math, but differ in how much control and abstraction they provide.”

This study emphasizes that deep learning frameworks, regardless of their abstraction level, fundamentally rely on the same mathematical principles of forward propagation, loss computation, and gradient-based optimization.

- The NumPy implementation exposed the underlying mechanics of neural networks, reinforcing the importance of understanding core concepts such as gradient descent and activation functions.

- TensorFlow/Keras demonstrated efficiency and ease of use through high-level APIs.

- while PyTorch showcased flexibility and transparency with its dynamic computation graph.

The experiment highlights that choosing a framework depends not only on performance but also on the desired level of control, interpretability, and development speed.